### ISSUE TITLE
Destroys Previous ZSH Configuration

### ISSUE THREAD

**Issue by funcyChaos** [Shift3/laptop#34]
I was running the PowerLevel10k ZSH theme and it got unset by the script.
Everything seems to still be there, I'm guessing it just got moved over to the default or other custom theme.

**Comment by funcyChaos** [comment]
Also discovered it destroys git configuration settings. Lost user.name/email, and init.defaultBranch

**Comment by funcyChaos** [comment]
Also does not install yarn

**Comment by DropsOfSerenity** [comment]
@funcyChaos Yeah it's going to setup your computer in a very specific way. However your files should not be destroyed. It should have backed up any files it was going to replace to `~/.filename.link.backup`. Check out the [link_dotfile](https://github.com/Shift3/laptop/blob/master/setup#L42-L51) function to see what it's doing behind the scenes.

Also give [this section](https://github.com/Shift3/laptop#maintaining-your-customizations) a read.

Lastly I'm not sure yarn is appropriate for install globally.  I'm not sure it's not either, but typically since we use `nvm` you would want to use a yarn version that is appropriate to the node version you are working on for a project.

**Comment by DropsOfSerenity** [comment]
Gonna close this for now @funcyChaos please open a new issue if you have anymore issues or want to resurface feedback.
